In [35]:
import yaml
import pandas as pd
import json

In [36]:
df = pd.read_csv("outputs_main_power/naive_simd/raw_db.csv")
(df["status"] == "fail").sum()
df[df["status"] == "fail"]

,run_id,timestamp_utc,fpga_bin_label,git_commit,git_branch,git_dirty,suite,case_id,exec_key,app,...,power_max_w,power_parse_error,log_file,elapsed_wall_s,samples,min_us,avg_us,max_us,p50_us,p95_us
51,20260621T151245157528Z,2026-06-21T15:13:30+00:00,naive_simd,f57736d40f02,fpint_improve,1,generation_merged_naive_simd,llama2_7b_generation_C4_fused_batch8_gen_kv_le...,d1277f91c5,rms_norm_layout_fused,...,NaN,NaN,/home/jaeyongjang/project.local/vortex/analysi...,10.137,0,NaN,NaN,NaN,NaN,NaN
52,20260621T151245157528Z,2026-06-21T15:13:41+00:00,naive_simd,f57736d40f02,fpint_improve,1,generation_merged_naive_simd,llama2_7b_generation_C4_fused_batch8_gen_kv_le...,d6d71b4dd9,rope_layout_fused,...,NaN,NaN,/home/jaeyongjang/project.local/vortex/analysi...,10.797,0,NaN,NaN,NaN,NaN,NaN
54,20260622T004947137617Z,2026-06-22T00:50:18+00:00,naive_simd,f57736d40f02,fpint_improve,1,prefill_merged_naive_simd,llama2_7b_prefill_all_sgemm_tcu_batch1_prefill...,9291e090d8,sgemm_tcu,...,11.628,NaN,/home/jaeyongjang/project.local/vortex/analysi...,8.643,0,NaN,NaN,NaN,NaN,NaN
55,20260622T004947137617Z,2026-06-22T00:50:26+00:00,naive_simd,f57736d40f02,fpint_improve,1,prefill_merged_naive_simd,llama2_7b_prefill_C4_alone_batch1_prefill_seq_...,67708ad49d,tile_scale_zp_w4a16,...,NaN,NaN,/home/jaeyongjang/project.local/vortex/analysi...,7.979,0,NaN,NaN,NaN,NaN,NaN
56,20260622T004947137617Z,2026-06-22T00:50:34+00:00,naive_simd,f57736d40f02,fpint_improve,1,prefill_merged_naive_simd,llama2_7b_prefill_C4_alone_batch1_prefill_seq_...,0739d889f4,tile_scale_zp_w4a16,...,NaN,NaN,/home/jaeyongjang/project.local/vortex/analysi...,8.509,0,NaN,NaN,NaN,NaN,NaN
57,20260622T004947137617Z,2026-06-22T00:50:43+00:00,naive_simd,f57736d40f02,fpint_improve,1,prefill_merged_naive_simd,llama2_7b_prefill_C4_alone_batch1_prefill_seq_...,a34125b147,tile_weight_w4a16,...,NaN,NaN,/home/jaeyongjang/project.local/vortex/analysi...,8.820,0,NaN,NaN,NaN,NaN,NaN
58,20260622T004947137617Z,2026-06-22T00:50:53+00:00,naive_simd,f57736d40f02,fpint_improve,1,prefill_merged_naive_simd,llama2_7b_prefill_C4_alone_batch1_prefill_seq_...,b86260cb54,tile_weight_w4a16,...,NaN,NaN,/home/jaeyongjang/project.local/vortex/analysi...,9.300,0,NaN,NaN,NaN,NaN,NaN
59,20260622T005118961255Z,2026-06-22T00:51:39+00:00,naive_simd,f57736d40f02,fpint_improve,1,generation_merged_naive_simd,llama2_7b_generation_C1_batch8_gen_kv_len512_q...,1ac96cdfef,sgemm_tcu,...,NaN,NaN,/home/jaeyongjang/project.local/vortex/analysi...,9.820,0,NaN,NaN,NaN,NaN,NaN
60,20260622T005118961255Z,2026-06-22T00:51:48+00:00,naive_simd,f57736d40f02,fpint_improve,1,generation_merged_naive_simd,llama2_7b_generation_C1_batch8_gen_kv_len512_q...,2c12012d23,sgemm_tcu,...,NaN,NaN,/home/jaeyongjang/project.local/vortex/analysi...,8.950,0,NaN,NaN,NaN,NaN,NaN
61,20260622T005118961255Z,2026-06-22T00:51:56+00:00,naive_simd,f57736d40f02,fpint_improve,1,generation_merged_naive_simd,llama2_7b_generation_C4_alone_batch8_gen_kv_le...,8976b564c3,tile_weight_w4a16,...,NaN,NaN,/home/jaeyongjang/project.local/vortex/analysi...,8.498,0,NaN,NaN,NaN,NaN,NaN
62,20260622T042957760295Z,2026-06-22T04:30:16+00:00,naive_simd,bd307143540b,fpint_improve,1,prefill_merged_naive_simd,llama2_7b_prefill_C4_fused_batch1_prefill_seq_...,0dfa8cfbb2,kv_cache_quant_layout_fused_w4a16,...,NaN,NaN,/home/jaeyongjang/project.local/vortex/analysi...,8.737,0,NaN,NaN,NaN,NaN,NaN
63,20260622T042957760295Z,2026-06-22T04:30:25+00:00,naive_simd,bd307143540b,fpint_improve,1,prefill_merged_naive_simd,llama2_7b_prefill_C4_fused_batch1_prefill_seq_...,915d5b4349,kv_cache_quant_layout_fused_w4a16,...,NaN,NaN,/home/jaeyongjang/project.local/vortex/analysi...,8.930,0,NaN,NaN,NaN,NaN,NaN
64,20260622T043032027136Z,2026-06-22T04:30:43+00:00,naive_simd,bd307143540b,fpint_improve,1,generation_merged_naive_simd,llama2_7b_generation_C4_fused_batch8_gen_kv_le...,864f37e638,kv_cache_quant_layout_fused_w4a16,...,NaN,NaN,/home/jaeyongjang/project.local/vortex/analysi...,8.874,0,NaN,NaN,NaN,NaN,NaN
65,20260622T043032027136Z,2026-06-22T04:30:52+00:00,naive_simd,bd307143540b,fpint_improve,1,generation_merged_naive_simd,llama2_7b_generation_C4_fused_batch8_gen_kv_le...,36838eca09,kv_cache_quant_layout_fused_w4a16,...,NaN,NaN,/home/jaeyongjang/project.local/vortex/analysi...,8.878,0,NaN,NaN,NaN,NaN,NaN

In [37]:
df = pd.read_csv("outputs_main/naive_simd/raw_db.csv")
print((df["status"] == "fail").sum())
failed = df["status"] == "fail"
print(df.columns)
df[failed][["fpga_bin_label", "suite", "app", "args", "shape_json", "returncode", "failure_phase", "failure_reason"]]

0
Index(['run_id', 'timestamp_utc', 'fpga_bin_label', 'git_commit', 'git_branch',
       'git_dirty', 'suite', 'case_id', 'exec_key', 'app', 'kind', 'op',
       'backend', 'variant', 'stage', 'name', 'args', 'shape_json',
       'calls_per_forward', 'fpga_bin_dir', 'xclbin_sha256', 'warmup',
       'iterations', 'source', 'status', 'returncode', 'failure_phase',
       'failure_reason', 'raw_csv', 'power_csv', 'power_summary',
       'measure_latency', 'measure_power', 'power_samples', 'power_elapsed_s',
       'power_min_w', 'power_avg_w', 'power_max_w', 'power_parse_error',
       'log_file', 'elapsed_wall_s', 'samples', 'min_us', 'avg_us', 'max_us',
       'p50_us', 'p95_us'],
      dtype='object')

Empty DataFrame
Columns: [fpga_bin_label, suite, app, args, shape_json, returncode, failure_phase, failure_reason]
Index: []

In [38]:
tcu_idx = df["app"] == "sgemm_tcu"
shape_jsons = df[tcu_idx]["shape_json"].values
df_ = df[tcu_idx]

for idx, i in enumerate(shape_jsons):
  data = json.loads(i)
  if data["M"] == 4:
    print(idx, data)

df_.iloc[64,:]

43 {'K': 4096, 'M': 4, 'N': 4096}
44 {'K': 4096, 'M': 4, 'N': 11008}
45 {'K': 11008, 'M': 4, 'N': 4096}
64 {'K': 128, 'M': 4, 'N': 512, 'grouped_query_attention': True, 'key_value_heads': 8, 'per_head': True, 'query_heads': 32, 'query_heads_per_kv': 4}
65 {'K': 512, 'M': 4, 'N': 128, 'grouped_query_attention': True, 'key_value_heads': 8, 'per_head': True, 'query_heads': 32, 'query_heads_per_kv': 4}
66 {'K': 128, 'M': 4, 'N': 1024, 'grouped_query_attention': True, 'key_value_heads': 8, 'per_head': True, 'query_heads': 32, 'query_heads_per_kv': 4}
67 {'K': 1024, 'M': 4, 'N': 128, 'grouped_query_attention': True, 'key_value_heads': 8, 'per_head': True, 'query_heads': 32, 'query_heads_per_kv': 4}
68 {'K': 128, 'M': 4, 'N': 2048, 'grouped_query_attention': True, 'key_value_heads': 8, 'per_head': True, 'query_heads': 32, 'query_heads_per_kv': 4}
69 {'K': 2048, 'M': 4, 'N': 128, 'grouped_query_attention': True, 'key_value_heads': 8, 'per_head': True, 'query_heads': 32, 'query_heads_per_kv': 4}
70 {'K': 128, 'M': 4, 'N': 4096, 'grouped_query_attention': True, 'key_value_heads': 8, 'per_head': True, 'query_heads': 32, 'query_heads_per_kv': 4}
71 {'K': 4096, 'M': 4, 'N': 128, 'grouped_query_attention': True, 'key_value_heads': 8, 'per_head': True, 'query_heads': 32, 'query_heads_per_kv': 4}

run_id                                          20260626T100346931517Z
timestamp_utc                                2026-06-26T10:04:15+00:00
fpga_bin_label                                              naive_simd
git_commit                                                77415dedd9ea
git_branch                                               fpint_improve
git_dirty                                                            1
suite                                     generation_merged_naive_simd
case_id              llama3_8b_generation_C1_batch1_gen_kv_len512_q...
exec_key                                                    9ca7742df3
app                                                          sgemm_tcu
kind                                                              gemm
op                                                            attn_qkT
backend                                                      sgemm_tcu
variant                                        all_sgemm_tcu_spinquant
stage                                                       generation
name                                                          attn_qkT
args                                                -m 4 -n 512 -k 128
shape_json           {"K": 128, "M": 4, "N": 512, "grouped_query_at...
calls_per_forward                                                256.0
fpga_bin_dir         /opt/vortex_fpga_bins/fpint/xrt_hw_u55c_c1_f10...
xclbin_sha256        f9d4c06cee4c6e36c642ff55483c0dd89e2a213a6dc344...
warmup                                                               0
iterations                                                           1
source                                                        explicit
status                                                            pass
returncode                                                           0
failure_phase                                                      NaN
failure_reason                                                     NaN
raw_csv              /home/jaeyongjang/project.local/vortex/analysi...
power_csv                                                          NaN
power_summary                                                      NaN
measure_latency                                                      1
measure_power                                                        0
power_samples                                                      NaN
power_elapsed_s                                                    NaN
power_min_w                                                        NaN
power_avg_w                                                        NaN
power_max_w                                                        NaN
power_parse_error                                                  NaN
log_file             /home/jaeyongjang/project.local/vortex/analysi...
elapsed_wall_s                                                   9.323
samples                                                            1.0
min_us                                                        3760.172
avg_us                                                        3760.172
max_us                                                        3760.172
p50_us                                                        3760.172
p95_us                                                        3760.172
Name: 431, dtype: object

In [39]:
df["variant"]

0                            all_sgemm_tcu_spinquant
1                            all_sgemm_tcu_spinquant
2                            all_sgemm_tcu_spinquant
3                            all_sgemm_tcu_spinquant
4                            all_sgemm_tcu_spinquant
                           ...
442    all_fpint_gemm_improve_alone_layout_spinquant
443    all_fpint_gemm_improve_alone_layout_spinquant
444    all_fpint_gemm_improve_alone_layout_spinquant
445    all_fpint_gemm_improve_alone_layout_spinquant
446    all_fpint_gemm_improve_alone_layout_spinquant
Name: variant, Length: 447, dtype: object

In [40]:
df = pd.read_csv("outputs_main/improve_tcol32/raw_db.csv")
print(df.columns)
failed = df["status"] == "failed"
print(failed.sum())

gemm_idx = df["app"] == "fpint_gemm_ffn_hw"
shape_jsons = df[gemm_idx]["shape_json"].values

for idx, i in enumerate(shape_jsons):
  data = json.loads(i)
  if data["M"] == 4:
    print(idx, data)

df_ = df[gemm_idx]
df_.iloc[33,:]

Index(['run_id', 'timestamp_utc', 'fpga_bin_label', 'git_commit', 'git_branch',
       'git_dirty', 'suite', 'case_id', 'exec_key', 'app', 'kind', 'op',
       'backend', 'variant', 'stage', 'name', 'args', 'shape_json',
       'calls_per_forward', 'fpga_bin_dir', 'xclbin_sha256', 'warmup',
       'iterations', 'source', 'status', 'returncode', 'failure_phase',
       'failure_reason', 'raw_csv', 'power_csv', 'power_summary',
       'measure_latency', 'measure_power', 'power_samples', 'power_elapsed_s',
       'power_min_w', 'power_avg_w', 'power_max_w', 'power_parse_error',
       'log_file', 'elapsed_wall_s', 'samples', 'min_us', 'avg_us', 'max_us',
       'p50_us', 'p95_us'],
      dtype='object')
0
33 {'K': 4096, 'M': 4, 'N': 4096, 'QBLK': 32, 'QDIR': 0, 'WTRANS': 0}
34 {'K': 4096, 'M': 4, 'N': 11008, 'QBLK': 32, 'QDIR': 0, 'WTRANS': 0}
35 {'K': 11008, 'M': 4, 'N': 4096, 'QBLK': 32, 'QDIR': 0, 'WTRANS': 0}
74 {'K': 128, 'M': 4, 'N': 512, 'QBLK': 128, 'QDIR': 0, 'WTRANS': 1, 'grouped_query_attention': True, 'key_value_heads': 8, 'per_head': True, 'query_heads': 32, 'query_heads_per_kv': 4}
75 {'K': 512, 'M': 4, 'N': 128, 'QBLK': 128, 'QDIR': 1, 'WTRANS': 0, 'grouped_query_attention': True, 'key_value_heads': 8, 'per_head': True, 'query_heads': 32, 'query_heads_per_kv': 4}
76 {'K': 128, 'M': 4, 'N': 1024, 'QBLK': 128, 'QDIR': 0, 'WTRANS': 1, 'grouped_query_attention': True, 'key_value_heads': 8, 'per_head': True, 'query_heads': 32, 'query_heads_per_kv': 4}
77 {'K': 1024, 'M': 4, 'N': 128, 'QBLK': 128, 'QDIR': 1, 'WTRANS': 0, 'grouped_query_attention': True, 'key_value_heads': 8, 'per_head': True, 'query_heads': 32, 'query_heads_per_kv': 4}
78 {'K': 128, 'M': 4, 'N': 2048, 'QBLK': 128, 'QDIR': 0, 'WTRANS': 1, 'grouped_query_attention': True, 'key_value_heads': 8, 'per_head': True, 'query_heads': 32, 'query_heads_per_kv': 4}
79 {'K': 2048, 'M': 4, 'N': 128, 'QBLK': 128, 'QDIR': 1, 'WTRANS': 0, 'grouped_query_attention': True, 'key_value_heads': 8, 'per_head': True, 'query_heads': 32, 'query_heads_per_kv': 4}
80 {'K': 128, 'M': 4, 'N': 4096, 'QBLK': 128, 'QDIR': 0, 'WTRANS': 1, 'grouped_query_attention': True, 'key_value_heads': 8, 'per_head': True, 'query_heads': 32, 'query_heads_per_kv': 4}
81 {'K': 4096, 'M': 4, 'N': 128, 'QBLK': 128, 'QDIR': 1, 'WTRANS': 0, 'grouped_query_attention': True, 'key_value_heads': 8, 'per_head': True, 'query_heads': 32, 'query_heads_per_kv': 4}

run_id                                          20260607T001621296549Z
timestamp_utc                                2026-06-07T00:19:39+00:00
fpga_bin_label                                          improve_tcol32
git_commit                                                799ea2c24559
git_branch                                               fpint_improve
git_dirty                                                            0
suite                                 generation_merged_improve_tcol32
case_id              llama2_7b_generation_C4_alone_batch4_gen_kv_le...
exec_key                                                    c15f0a8053
app                                                  fpint_gemm_ffn_hw
kind                                                              gemm
op                                                              q_proj
backend                                             fpint_gemm_improve
variant                  all_fpint_gemm_improve_alone_layout_spinquant
stage                                                       generation
name                                                            q_proj
args                              -m 4 -n 4096 -k 4096 -q 32 -t 0 -d 0
shape_json           {"K": 4096, "M": 4, "N": 4096, "QBLK": 32, "QD...
calls_per_forward                                                 32.0
fpga_bin_dir         /opt/vortex_fpga_bins/fpint/xrt_hw_u55c_c1_f10...
xclbin_sha256        a768b653f04e3cf72df91b5e6aa4f34e6bbbe642fa4431...
warmup                                                               0
iterations                                                           1
source                                                        explicit
status                                                            pass
returncode                                                           0
failure_phase                                                      NaN
failure_reason                                                     NaN
raw_csv              /home/jaeyongjang/project.local/vortex/analysi...
power_csv                                                          NaN
power_summary                                                      NaN
measure_latency                                                      1
measure_power                                                        0
power_samples                                                      NaN
power_elapsed_s                                                    NaN
power_min_w                                                        NaN
power_avg_w                                                        NaN
power_max_w                                                        NaN
power_parse_error                                                  NaN
log_file             /home/jaeyongjang/project.local/vortex/analysi...
elapsed_wall_s                                                  10.104
samples                                                            1.0
min_us                                                       11183.611
avg_us                                                       11183.611
max_us                                                       11183.611
p50_us                                                       11183.611
p95_us                                                       11183.611
Name: 33, dtype: object