In [23]:
from pathlib import Path

import yaml
import pandas as pd
import json
import re

In [24]:
pd.set_option("display.max_columns", None)      # 모든 column 표시
pd.set_option("display.max_rows", None)         # 모든 row 표시
pd.set_option("display.max_colwidth", None)     # column 안의 문자열 생략 안 함
pd.set_option("display.width", None)            # 출력 폭 제한 완화
pd.set_option("display.expand_frame_repr", False)  # 여러 줄로 쪼개서 출력하지 않음

In [25]:
df = pd.read_csv("./outputs_llama3_main/C4/raw_db.csv")

In [26]:
df

                     run_id              timestamp_utc fpga_bin_label    git_commit git_branch  git_dirty                 suite                                                                                                       case_id    exec_key                                app          kind                                    op                            backend                                        variant       stage                                  name                                                                                                                                                                                                                                             args                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    shape_json  calls_per_forward                                                         fpga_bin_dir                                                     xclbin_sha256  warmup  iterations    source status  returncode  failure_phase  failure_reason                                                                                                                                              raw_csv                                                                                                                                              power_csv                                                                                                                                                  power_summary  measure_latency  measure_power  power_samples  power_elapsed_s  power_min_w  power_avg_w  power_max_w  power_std_w  power_total_min_w  power_total_avg_w  power_total_max_w  power_idle_w  power_idle_std_w  power_idle_vcc_avg_w  power_idle_pcie_avg_w  power_vcc_min_w  power_vcc_avg_w  power_vcc_max_w  power_pcie_min_w  power_pcie_avg_w  power_pcie_max_w  power_dynamic_avg_w  power_dynamic_peak_w  power_dynamic_stderr_w  power_dynamic_energy_j  power_latency  power_fpga_cycle  power_kernel_iterations  power_kernel_iterations_auto  power_target_sec power_source  power_raw_truncated  power_parse_error                                                                                                                                              log_file  elapsed_wall_s  samples        min_us        avg_us        max_us        p50_us        p95_us  fpga_cycle_samples  fpga_cycle_min  fpga_cycle_avg  fpga_cycle_max  fpga_cycle_p50  fpga_cycle_p95    fpga_cycle  fpga_cycle_parse_error
0    20260722T055123488761Z  2026-07-22T05:53:04+00:00             C4  5a18d224a665      fpint          1     prefill_merged_C4                       llama3_8b_prefill_all_sgemm_tcu_batch1_prefill_seq_len1024_qblk32_prefill_residual_attn  854e98bea8                              eladd         eladd                         residual_attn                              eladd                        all_sgemm_tcu_spinquant     prefill                         residual_attn                                                                                                                                                                                                                                       -n 4194304                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             {"size": 4194304}               32.0  /opt/vortex_fpga_bins/fpint/xrt_hw_u55c_c_f100_fpint_6de40e376b/bin  b9385ecf73b9390bfc5bf49bfbfe56052ccad15068933862abe2af378c568f5e       0           1  explicit   pass           0            NaN             NaN  /home/jaeyongjang/project.local/vortex_fpint/analysis_workspace/latency_on_hw/outputs_llama3_main/C4/runs/20260722T055123488761Z/raw/854e98bea8.csv  /home/jaeyongjang/project.local/vortex_fpint/analysis_workspace/latency_on_hw/outputs_llama3_main/C4/runs/20260722T055123488761Z/power/854e98bea8.csv  /home/jaeyongjang/project.local/vortex_fpint/analysis_workspace/latency_on_hw/outputs_llama3_main/C4/runs/20260722T055123488761Z/power/854e98bea8.summary.csv                1              1            152        19.974214    35.111648    37.349515    37.613936     0.386059          35.111648          37.349515          37.613936     35.121389          0.007723             11.575755              23.545635          11.6280        12.531313          12.7544         23.483648         24.818202         24.859536             2.228125              2.492547                0.031400               44.505052            NaN               NaN                       48                             1              20.0     separate                    0                NaN  /home/jaeyongjang/project.local/vortex_fpint/analysis_workspace/latency_on_hw/outputs_llama3_main/C4/runs/20260722T055123488761Z/logs/854e98bea8.log          38.488        1  4.187217e+05  4.187217e+05  4.187217e+05  4.187217e+05  4.187217e+05                   1        41793536        41793536        41793536        41793536        41793536      41793536                     NaN
1    20260722T055123488761Z  2026-07-22T05:53:46+00:00             C4  5a18d224a665      fpint          1     prefill_merged_C4                       llama3_8b_prefill_all_sgemm_tcu_batch1_prefill_seq_len2048_qblk32_prefill_residual_attn  f0cb78dfd3                              eladd         eladd                         residual_attn                              eladd                        all_sgemm_tcu_spinquant     prefill                         residual_attn                                                                                                                                                                                                                                       -n 8388608                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             {"size": 8388608}               32.0  /opt/vortex_fpga_bins/fpint/xrt_hw_u55c_c_f100_fpint_6de40e376b/bin  b9385ecf73b9390bfc5bf49bfbfe56052ccad15068933862abe2af378c568f5e       0           1  explicit   pass           0            NaN             NaN  /home/jaeyongjang/project.local/vortex_fpint/analysis_workspace/latency_on_hw/outputs_llama3_main/C4/runs/20260722T055123488761Z/raw/f0cb78dfd3.csv  /home/jaeyongjang/project.local/vortex_fpint/analysis_workspace/latency_on_hw/outputs_llama3_main/C4/runs/20260722T055123488761Z/power/f0cb78dfd3.csv  /home/jaeyongjang/project.local/vortex_fpint/analysis_workspace/latency_on_hw/outputs_llama3_main/C4/runs/20260722T055123488761Z/power/f0cb78dfd3.summary.csv                1              1            153        19.973278    35.041256    37.408819    37.684268     0.492645          35.041256          37.408819          37.684268     35.376699          0.319359             11.631267              23.745432          11.4602        12.555131          12.7429         23.581056         24.853688         24.944768             2.032120              2.307569                0.100426               40.588097            NaN               NaN                       24                             1              20.0     separate                    0                NaN  /home/jaeyongjang/project.local/vortex_fpint/analysis_workspace/latency_on_hw/outputs_llama3_main/C4/runs/20260722T055123488761Z/logs/f0cb78dfd3.log          41.219        1  8.351610e+05  8.351610e+05  8.351610e+05  8.351610e+05  8.351610e+05                   1        83396078        83396078        83396078        83396078        83396078      83396078                     NaN
2    20260722T055123488761Z  2026-07-22T05:54:35+00:00             C4  5a18d224a665      fpint          1     prefill_merged_C4                       llama3_8b_prefill_all_sgemm_tcu_batch1_prefill_seq_len4096_qblk32_prefill_residual_attn  5560c97d9c                              eladd         eladd                         residual_attn                              eladd                        all_sgemm_tcu_spinquant     prefill                         residual_attn                                                                                                                                                                                                                                      -n 16777216                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {"size": 16777216}               32.0  /opt/vortex_fpga_bins/fpint/xrt_hw_u55c_c_f100_fpint_6de40e376b/bin  b9385ecf73b9390bfc5bf49bfbfe56052ccad15068933862abe2af378c568f5e       0           1  explicit   pass           0            NaN             NaN  /home/jaeyongjang/project.local/vortex_fpint/analysis_workspace/latency_on_hw/outputs_llama3_main/C4/runs/20260722T055123488761Z/raw/5560c97d9c.csv  /home/jaeyongjang/project.local/vortex_fpint/analysis_workspace/latency_on_hw/outputs_llama3_main/C4/runs/20260722T055123488761Z/power/5560c97d9c.csv  /home/jaeyongjang/project.local/vortex_fpint/analysis_workspace/latency_on_hw/outputs_llama3_main/C4/runs/20260722T055123488761Z/power/5560c97d9c.summary.csv                1              1            166        21.637537    35.038056    37.440622    37.687668     0.436307          35.038056          37.440622          37.687668     35.102565          0.041432             11.521509              23.581056          11.4570        12.559099          12.7429         23.581056         24.881522         24.944768             2.338057              2.585103                0.036095               50.589783            NaN               NaN                       13                             1              20.0     separate                    0                NaN  /home/jaeyongjang/project.local/vortex_fpint/analysis_workspace/latency_on_hw/outputs_llama3_main/C4/runs/20260722T055123488761Z/logs/5560c97d9c.log          49.129        1  1.666801e+06  1.666801e+06  1.666801e+06  1.666801e+06  1.666801e+06                   1       166608960       166608960       166608960       166608960       166608960     166608960                     NaN
3    20260722T055123488761Z  2026-07-22T05:55:40+00:00             C4  5a18d224a665      fpint          1     prefill_merged_C4                       llama3_8b_prefill_all_sgemm_tcu_batch1_prefill_seq_len8192_qblk32_prefill_residual_attn  2da94d119e                              eladd         eladd                         residual_attn                              eladd                        all_sgemm_tcu_spinquant     prefill                         residual_attn                                                                                                                                                                                                                                      -n 33554432                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {"size": 33554432}               32.0  /opt/vortex_fpga_bins/fpint/xrt_hw_u55c_c_f100_fpint_6de40e376b/bin  b9385ecf73b9390bfc5bf49bfbfe56052ccad15068933862abe2af378c568f5e       0           1  explicit   pass           0            NaN             NaN  /home/jaeyongjang/project.local/vortex_fpint/analysis_workspace/latency_on_hw/outputs_llama3_main/C4/runs/20260722T055123488761Z/raw/2da94d119e.csv  /home/jaeyongjang/project.local/vortex_fpint/analysis_workspace/latency_on_hw/outputs_llama3_main/C4/runs/20260722T055123488761Z/power/2da94d119e.csv  /home/jaeyongjang/project.local/vortex_fpint/analysis_workspace/latency_on_hw/outputs_llama3_main/C4/runs/20260722T055123488761Z/power/2da94d119e.summary.csv                1              1            179        23.301488    35.297856    37.485632    37.699168     0.381512          35.297856          37.485632          37.699168     35.235674          0.039937             11.654618              23.581056          11.7168        12.590331          12.7544         23.581056         24.895301         24.944768             2.249958              2.463494                0.030954               52.427360            NaN               NaN                        7                             1              20.0     separate                    0                NaN  /home/jaeyongjang/project.local/vortex_fpint/analysis_workspace/latency_on_hw/outputs_llama3_main/C4/runs/20260722T055123488761Z/logs/2da94d119e.log          64.609        1  3.331587e+06  3.331587e+06  3.331587e+06  3.331587e+06  3.331587e+06                   1       333020910       333020910       333020910       333020910       333020910     333020910                     NaN
4    20260722T055123488761Z  2026-07-22T05:57:19+00:00             C4  5a18d224a665      fpint          1     prefill_merged_C4                      llama3_8b_prefill_all_sgemm_tcu_batch1_prefill_seq_len16384_qblk32_prefill_residual_attn  38c304f4cd                              eladd         eladd                         residual_attn                              eladd                        all_sgemm_tcu_spinquant     prefill                         residual_attn                                                                                                                                                                                                                                      -n 67108864                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {"size": 67108864}               32.0  /opt/vortex_fpga_bins/fpint/xrt_hw_u55c_c_f100_fpint_6de40e376b/bin  b9385ecf73b9390bfc5bf49bfbfe56052ccad15068933862abe2af378c568f5e       0           1  explicit   pass           0            NaN             NaN  /home/jaeyongjang/project.local/vortex_fpint/analysis_workspace/latency_on_hw/outputs_llama3_main/C4/runs/20260722T055123488761Z/raw/38c304f4cd.csv  /home/jaeyongjang/project.local/vortex_fpint/analysis_workspace/latency_on_hw/outputs_llama3_main/C4/runs/20260722T055123488761Z/power/38c304f4cd.csv  /home/jaeyongjang/project.local/vortex_fpint/analysis_workspace/latency_on_hw/outputs_llama3_main/C4/runs/20260722T055123488761Z/power/38c304f4cd.summary.csv                1              1            203        26.628755    35.212356    37.481748    37.699168     0.302821          35.212356          37.481748          37.699168     35.212356          0.000000             11.631300              23.581056          11.6313        12.569351          12.7544         23.581056         24.912398         24.944768             2.269392              2.486812                0.021254               60.431091            NaN               NaN                        4                             1              20.0     separate                    0                NaN  /home/jaeyongjang/project.local/vortex_fpint/analysis_workspace/latency_on_hw/outputs_llama3_main/C4/runs/20260722T055123488761Z/logs/38c304f4cd.log          99.039        1  6.659236e+06  6.659236e+06  6.659236e+06  6.659236e+06  6.659236e+06                   1       665839933       665839933       665839933       665839933       665839933     665839933                     NaN

In [21]:
# Compare every layout-fused vector kernel with its standalone counterpart.
# This is a direct kernel-cycle comparison; graph-level tile/detile savings are not included.
layout_to_standalone = {
    "eladd_layout_fused": "eladd",
    "elmul_layout_fused": "elmul",
    "hadamard_layout_fused": "hadamard",
    "head_concat_layout_fused": "head_concat",
    "kv_cache_quant_layout_fused_w4a16": "kv_cache_quant_w4a16",
    "rms_norm_layout_fused": "rmsnorm",
    "rope_layout_fused": "rope",
    "silu_layout_fused": "silu",
    "softmax_layout_fused": "softmax",
}
target_apps = set(layout_to_standalone) | set(layout_to_standalone.values())

ops = df[df["status"].eq("pass") & df["app"].isin(target_apps)].copy()
ops["timestamp_utc"] = pd.to_datetime(ops["timestamp_utc"], utc=True)
ops = (
    ops.sort_values("timestamp_utc")
       .drop_duplicates(["app", "stage", "name", "args"], keep="last")
)
ops["shape"] = ops["shape_json"].map(json.loads)

# Normalize the standalone/fused argument conventions to the same logical work shape.
shape_fields = {
    "eladd_layout_fused": ("size",),
    "elmul_layout_fused": ("size",),
    "hadamard_layout_fused": ("rows", "dim"),
    "head_concat_layout_fused": ("batch", "seq", "heads", "headdim"),
    "kv_cache_quant_layout_fused_w4a16": ("K", "N", "QBLK", "QDIR", "WTRANS"),
    "rms_norm_layout_fused": ("batch", "seq", "hidden"),
    "rope_layout_fused": ("batch", "seq", "heads", "headdim", "maxseq", "offset"),
    "silu_layout_fused": ("size",),
    "softmax_layout_fused": ("batch", "heads", "seqq", "seqk", "mask"),
}
app_to_layout = {
    **{app: app for app in layout_to_standalone},
    **{standalone: layout for layout, standalone in layout_to_standalone.items()},
}
ops["pair_id"] = ops["app"].map(app_to_layout)
ops["work_shape"] = ops.apply(
    lambda row: tuple(
        (field, row["shape"].get(field)) for field in shape_fields[row["pair_id"]]
    ),
    axis=1,
)

# Match physical executions by app pair and work shape, not semantic kernel name.
# Merged suites intentionally deduplicate identical executions (for example,
# an R3-K Hadamard shape can reuse an R3-Q Hadamard row with the same args).
match_key = ["stage", "pair_id", "work_shape"]
layout_fused = ops[ops["app"].isin(layout_to_standalone)]
standalone = (
    ops[ops["app"].isin(layout_to_standalone.values())]
    .drop_duplicates(match_key, keep="last")
)
compare = layout_fused.merge(
    standalone, on=match_key, how="left", suffixes=("_fused", "_standalone"),
)
compare["fused_over_standalone"] = (
    compare["fpga_cycle_fused"] / compare["fpga_cycle_standalone"]
)
compare["matched"] = compare["fpga_cycle_standalone"].notna()

compare_table = compare.rename(columns={
    "name_fused": "name",
    "name_standalone": "standalone_name",
    "app_standalone": "standalone_app",
    "app_fused": "layout_fused_app",
    "args_standalone": "standalone_args",
    "args_fused": "layout_fused_args",
    "calls_per_forward_fused": "calls_per_forward",
})[[
    "stage", "name", "standalone_name", "work_shape", "calls_per_forward",
    "standalone_app", "layout_fused_app", "standalone_args", "layout_fused_args",
    "fpga_cycle_standalone", "fpga_cycle_fused", "fused_over_standalone", "matched",
]].sort_values(["stage", "layout_fused_app", "name", "work_shape"])

comparison_summary = (
    compare_table[compare_table["matched"]]
    .groupby(["stage", "standalone_app", "layout_fused_app"], dropna=False)
    ["fused_over_standalone"]
    .agg(samples="size", median="median", minimum="min", maximum="max")
    .reset_index()
)
display(comparison_summary)
print(f"unmatched layout-fused rows: {(~compare_table['matched']).sum()}")
compare_table.reset_index(drop=True)

         stage        standalone_app                   layout_fused_app  samples     median    minimum    maximum
0   generation                 eladd                 eladd_layout_fused        3   1.482717   1.287020   1.728291
1   generation                 elmul                 elmul_layout_fused        3   2.884174   1.960949   3.912283
2   generation              hadamard              hadamard_layout_fused        9   0.515968   0.432652   3.427587
3   generation           head_concat           head_concat_layout_fused        3   0.920648   0.688870   1.150033
4   generation  kv_cache_quant_w4a16  kv_cache_quant_layout_fused_w4a16       12  12.945608  12.537917  13.303138
5   generation               rmsnorm              rms_norm_layout_fused        3   1.208016   0.804880   1.728979
6   generation                  rope                  rope_layout_fused       36   1.327452   1.099556   1.795605
7   generation                  silu                  silu_layout_fused        3   1.460697   0.865649   2.295428
8   generation               softmax               softmax_layout_fused       18   1.455953   1.203108   1.558642
9      prefill                 eladd                 eladd_layout_fused        6   2.285031   2.276834   2.303904
10     prefill                 elmul                 elmul_layout_fused        6   1.448982   1.447407   1.449328
11     prefill              hadamard              hadamard_layout_fused       18   0.421656   0.421319   1.349708
12     prefill           head_concat           head_concat_layout_fused        6   0.210376   0.206360   0.218829
13     prefill  kv_cache_quant_w4a16  kv_cache_quant_layout_fused_w4a16       12   3.192206   1.832899   4.536585
14     prefill               rmsnorm              rms_norm_layout_fused        6   0.759912   0.759250   0.761007
15     prefill                  rope                  rope_layout_fused       12   0.892023   0.887779   0.896913
16     prefill                  silu                  silu_layout_fused        6   0.474801   0.474647   0.474930
17     prefill               softmax               softmax_layout_fused        6   1.407462   1.332995   1.475225

unmatched layout-fused rows: 0

          stage                               name                    standalone_name                                                                             work_shape  calls_per_forward        standalone_app                   layout_fused_app                                                       standalone_args                                                                                                                                                                                                                                layout_fused_args  fpga_cycle_standalone  fpga_cycle_fused  fused_over_standalone  matched
0    generation                      residual_attn                      residual_attn                                                                        ((size, 4096),)               32.0                 eladd                 eladd_layout_fused                                                               -n 4096                                                                                                                                                                                                                                     -m 1 -k 4096                 234423            301707               1.287020     True
1    generation                      residual_attn                      residual_attn                                                                        ((size, 8192),)               32.0                 eladd                 eladd_layout_fused                                                               -n 8192                                                                                                                                                                                                                                     -m 2 -k 4096                 272775            404448               1.482717     True
2    generation                      residual_attn                      residual_attn                                                                       ((size, 16384),)               32.0                 eladd                 eladd_layout_fused                                                              -n 16384                                                                                                                                                                                                                                     -m 4 -k 4096                 359543            621395               1.728291     True
3    generation                          mlp_elmul                          mlp_elmul                                                                       ((size, 14336),)               32.0                 elmul                 elmul_layout_fused                                                              -n 14336                                                                                                                                                                                                                                    -m 1 -k 14336                 327806           1282470               3.912283     True
4    generation                          mlp_elmul                          mlp_elmul                                                                       ((size, 28672),)               32.0                 elmul                 elmul_layout_fused                                                              -n 28672                                                                                                                                                                                                                                    -m 2 -k 14336                 466191           1344576               2.884174     True
5    generation                          mlp_elmul                          mlp_elmul                                                                       ((size, 57344),)               32.0                 elmul                 elmul_layout_fused                                                              -n 57344                                                                                                                                                                                                                                    -m 4 -k 14336                 747152           1465127               1.960949     True
6    generation            spinquant_r3_k_hadamard            spinquant_r3_k_hadamard                                                                ((rows, 8), (dim, 128))               32.0              hadamard              hadamard_layout_fused                                                      -rows 8 -dim 128                                                                                                                                                                                                                                 -m 1 -n 8 -k 128                 397978            229669               0.577090     True
7    generation            spinquant_r3_k_hadamard            spinquant_r3_k_hadamard                                                               ((rows, 16), (dim, 128))               32.0              hadamard              hadamard_layout_fused                                                     -rows 16 -dim 128                                                                                                                                                                                                                                -m 1 -n 16 -k 128                 729718            376511               0.515968     True
8    generation            spinquant_r3_k_hadamard            spinquant_r3_q_hadamard                                                               ((rows, 32), (dim, 128))               32.0              hadamard              hadamard_layout_fused                                                     -rows 32 -dim 128                                                                                                                                                                                                                                -m 1 -n 32 -k 128                1389710            654820               0.471192     True
9    generation            spinquant_r3_q_hadamard            spinquant_r3_q_hadamard                                                               ((rows, 32), (dim, 128))               32.0              hadamard              hadamard_layout_fused                                                     -rows 32 -dim 128                                                                                                                                                                                                                                 -m 4 -n 8 -k 128                1389710            658368               0.473745     True
10   generation            spinquant_r3_q_hadamard            spinquant_r3_q_hadamard                                                               ((rows, 64), (dim, 128))               32.0              hadamard              hadamard_layout_fused                                                     -rows 64 -dim 128                                                                                                                                                                                                                                -m 4 -n 16 -k 128                2714744           1226987               0.451972     True
11   generation            spinquant_r3_q_hadamard            spinquant_r3_q_hadamard                                                              ((rows, 128), (dim, 128))               32.0              hadamard              hadamard_layout_fused                                                    -rows 128 -dim 128                                                                                                                                                                                                                                -m 4 -n 32 -k 128                5362137           2319937               0.432652     True
12   generation          spinquant_r4_mlp_hadamard          spinquant_r4_mlp_hadamard                                                              ((rows, 1), (dim, 14336))               32.0              hadamard              hadamard_layout_fused                                                    -rows 1 -dim 14336                                                                                                                                                                                                    -m 1 -n 1 -k 14336 --layout-from gemm_a_tiled                 615601           2110026               3.427587     True
13   generation          spinquant_r4_mlp_hadamard          spinquant_r4_mlp_hadamard                                                              ((rows, 2), (dim, 14336))               32.0              hadamard              hadamard_layout_fused                                                    -rows 2 -dim 14336                                                                                                                                                                                                    -m 2 -n 1 -k 14336 --layout-from gemm_a_tiled                1159254           2254134               1.944469     True
14   generation          spinquant_r4_mlp_hadamard          spinquant_r4_mlp_hadamard                                                              ((rows, 4), (dim, 14336))               32.0              hadamard              hadamard_layout_fused                                                    -rows 4 -dim 14336                                                                                                                                                                                                    -m 4 -n 1 -k 14336 --layout-from gemm_a_tiled                2245849           2706817               1.205253     True
15   generation                   attn_head_concat                   attn_head_concat                                    ((batch, 1), (seq, 1), (heads, 32), (headdim, 128))               32.0           head_concat           head_concat_layout_fused                                -batch 1 -seq 1 -heads 32 -headdim 128                                                                                                                                                                                  -batch 1 -seq 1 -heads 32 -headdim 128 --layout-to gemm_a_tiled                 187486            215615               1.150033     True
16   generation                   attn_head_concat                   attn_head_concat                                    ((batch, 2), (seq, 1), (heads, 32), (headdim, 128))               32.0           head_concat           head_concat_layout_fused                                -batch 2 -seq 1 -heads 32 -headdim 128                                                                                                                                                                                  -batch 2 -seq 1 -heads 32 -headdim 128 --layout-to gemm_a_tiled                 246586            227019               0.920648     True
17   generation                   attn_head_concat                   attn_head_concat                                    ((batch, 4), (seq, 1), (heads, 32), (headdim, 128))               32.0           head_concat           head_concat_layout_fused                                -batch 4 -seq 1 -heads 32 -headdim 128                                                                                                                                                                                  -batch 4 -seq 1 -heads 32 -headdim 128 --layout-to gemm_a_tiled                 345142            237758               0.688870     True
18   generation  kv_cache_quant_rope_k_to_attn_qkT  kv_cache_quant_rope_k_to_attn_qkT                                ((K, 1), (N, 128), (QBLK, 128), (QDIR, 1), (WTRANS, 1))              256.0  kv_cache_quant_w4a16  kv_cache_quant_layout_fused_w4a16                                          -k 1 -n 128 -q 128 -d 1 -t 1    -k 1 -n 128 -q 128 -d 1 -t 1 --gemm-qdir 0 --source-transposed --layout-from gemm_a_tiled --quant-mode spinquant_signed_asymmetric --source-total-n 128 --head-col-offset 0 --cache-update append --cache-capacity 1024 --cache-position 1023                  83158           1069714              12.863633     True
19   generation  kv_cache_quant_rope_k_to_attn_qkT  kv_cache_quant_rope_k_to_attn_qkT                                ((K, 1), (N, 128), (QBLK, 128), (QDIR, 1), (WTRANS, 1))              256.0  kv_cache_quant_w4a16  kv_cache_quant_layout_fused_w4a16                                          -k 1 -n 128 -q 128 -d 1 -t 1    -k 1 -n 128 -q 128 -d 1 -t 1 --gemm-qdir 0 --source-transposed --layout-from gemm_a_tiled --quant-mode spinquant_signed_asymmetric --source-total-n 128 --head-col-offset 0 --cache-update append --cache-capacity 2048 --cache-position 2047                  83158           1086321              13.063337     True
20   generation  kv_cache_quant_rope_k_to_attn_qkT  kv_cache_quant_rope_k_to_attn_qkT                                ((K, 1), (N, 128), (QBLK, 128), (QDIR, 1), (WTRANS, 1))              256.0  kv_cache_quant_w4a16  kv_cache_quant_layout_fused_w4a16                                          -k 1 -n 128 -q 128 -d 1 -t 1    -k 1 -n 128 -q 128 -d 1 -t 1 --gemm-qdir 0 --source-transposed --layout-from gemm_a_tiled --quant-mode spinquant_signed_asymmetric --source-total-n 128 --head-col-offset 0 --cache-update append --cache-capacity 4096 --cache-position 4095                  83158           1064326              12.798841     True
21   generation  kv_cache_quant_rope_k_to_attn_qkT  kv_cache_quant_rope_k_to_attn_qkT                                ((K, 1), (N, 128), (QBLK, 128), (QDIR, 1), (WTRANS, 1))              256.0  kv_cache_quant_w4a16  kv_cache_quant_layout_fused_w4a16                                          -k 1 -n 128 -q 128 -d 1 -t 1    -k 1 -n 128 -q 128 -d 1 -t 1 --gemm-qdir 0 --source-transposed --layout-from gemm_a_tiled --quant-mode spinquant_signed_asymmetric --source-total-n 128 --head-col-offset 0 --cache-update append --cache-capacity 8192 --cache-position 8191                  83158           1057719              12.719390     True
22   generation  kv_cache_quant_rope_k_to_attn_qkT  kv_cache_quant_rope_k_to_attn_qkT                                ((K, 1), (N, 128), (QBLK, 128), (QDIR, 1), (WTRANS, 1))              256.0  kv_cache_quant_w4a16  kv_cache_quant_layout_fused_w4a16                                          -k 1 -n 128 -q 128 -d 1 -t 1  -k 1 -n 128 -q 128 -d 1 -t 1 --gemm-qdir 0 --source-transposed --layout-from gemm_a_tiled --quant-mode spinquant_signed_asymmetric --source-total-n 128 --head-col-offset 0 --cache-update append --cache-capacity 16384 --cache-position 16383                  83158           1051775              12.647911     True
23   generation  kv_cache_quant_rope_k_to_attn_qkT  kv_cache_quant_rope_k_to_attn_qkT                                ((K, 1), (N, 128), (QBLK, 128), (QDIR, 1), (WTRANS, 1))              256.0  kv_cache_quant_w4a16  kv_cache_quant_layout_fused_w4a16                                          -k 1 -n 128 -q 128 -d 1 -t 1  -k 1 -n 128 -q 128 -d 1 -t 1 --gemm-qdir 0 --source-transposed --layout-from gemm_a_tiled --quant-mode spinquant_signed_asymmetric --source-total-n 128 --head-col-offset 0 --cache-update append --cache-capacity 32768 --cache-position 32767                  83158           1058278              12.726112     True
24   generation  kv_cache_quant_v_cache_to_attn_pv  kv_cache_quant_v_cache_to_attn_pv                                ((K, 1), (N, 128), (QBLK, 128), (QDIR, 1), (WTRANS, 0))              256.0  kv_cache_quant_w4a16  kv_cache_quant_layout_fused_w4a16                                          -k 1 -n 128 -q 128 -d 1 -t 0                        -k 1 -n 128 -q 128 -d 1 -t 0 --gemm-qdir 1 --layout-from gemm_c_tiled --quant-mode spinquant_signed_symmetric --source-total-n 1024 --head-col-offset 0 --cache-update append --cache-capacity 1024 --cache-position 1023                  82154           1070268              13.027582     True
25   generation  kv_cache_quant_v_cache_to_attn_pv  kv_cache_quant_v_cache_to_attn_pv                                ((K, 1), (N, 128), (QBLK, 128), (QDIR, 1), (WTRANS, 0))              256.0  kv_cache_quant_w4a16  kv_cache_quant_layout_fused_w4a16                                          -k 1 -n 128 -q 128 -d 1 -t 0                        -k 1 -n 128 -q 128 -d 1 -t 0 --gemm-qdir 1 --layout-from gemm_c_tiled --quant-mode spinquant_signed_symmetric --source-total-n 1024 --head-col-offset 0 --cache-update append --cache-capacity 2048 --cache-position 2047                  82154           1085806              13.216715     True
26   generation  kv_cache_quant_v_cache_to_attn_pv  kv_cache_quant_v_cache_to_attn_pv                                ((K, 1), (N, 128), (QBLK, 128), (QDIR, 1), (WTRANS, 0))              256.0  kv_cache_quant_w4a16  kv_cache_quant_layout_fused_w4a16                                          -k 1 -n 128 -q 128 -d 1 -t 0                        -k 1 -n 128 -q 128 -d 1 -t 0 --gemm-qdir 1 --layout-from gemm_c_tiled --quant-mode spinquant_signed_symmetric --source-total-n 1024 --head-col-offset 0 --cache-update append --cache-capacity 4096 --cache-position 4095                  82154           1083513              13.188804     True
27   generation  kv_cache_quant_v_cache_to_attn_pv  kv_cache_quant_v_cache_to_attn_pv                                ((K, 1), (N, 128), (QBLK, 128), (QDIR, 1), (WTRANS, 0))              256.0  kv_cache_quant_w4a16  kv_cache_quant_layout_fused_w4a16                                          -k 1 -n 128 -q 128 -d 1 -t 0                        -k 1 -n 128 -q 128 -d 1 -t 0 --gemm-qdir 1 --layout-from gemm_c_tiled --quant-mode spinquant_signed_symmetric --source-total-n 1024 --head-col-offset 0 --cache-update append --cache-capacity 8192 --cache-position 8191                  82154           1077749              13.118643     True
28   generation  kv_cache_quant_v_cache_to_attn_pv  kv_cache_quant_v_cache_to_attn_pv                                ((K, 1), (N, 128), (QBLK, 128), (QDIR, 1), (WTRANS, 0))              256.0  kv_cache_quant_w4a16  kv_cache_quant_layout_fused_w4a16                                          -k 1 -n 128 -q 128 -d 1 -t 0                      -k 1 -n 128 -q 128 -d 1 -t 0 --gemm-qdir 1 --layout-from gemm_c_tiled --quant-mode spinquant_signed_symmetric --source-total-n 1024 --head-col-offset 0 --cache-update append --cache-capacity 16384 --cache-position 16383                  82154           1092906              13.303138     True
29   generation  kv_cache_quant_v_cache_to_attn_pv  kv_cache_quant_v_cache_to_attn_pv                                ((K, 1), (N, 128), (QBLK, 128), (QDIR, 1), (WTRANS, 0))              256.0  kv_cache_quant_w4a16  kv_cache_quant_layout_fused_w4a16                                          -k 1 -n 128 -q 128 -d 1 -t 0                      -k 1 -n 128 -q 128 -d 1 -t 0 --gemm-qdir 1 --layout-from gemm_c_tiled --quant-mode spinquant_signed_symmetric --source-total-n 1024 --head-col-offset 0 --cache-update append --cache-capacity 32768 --cache-position 32767                  82154           1030040              12.537917     True

In [22]:
# Rank layout-fused kernels by their weighted contribution to the C4-vs-C3 E2E gap.
# We expand the original model structures so merged-suite execution deduplication
# does not under-count kernels whose physical args are reused across workloads.
FPGA_FREQ_MHZ = 100.0
WORKLOAD_WEIGHTS = {}  # Optional: {workload_id: weight}; unspecified workloads use 1.0.
structure_files = {
    "prefill": Path("./generated_suites/llama3_8b_main/C4_fused_prefill/model_structure.json"),
    "generation": Path("./generated_suites/llama3_8b_main/C4_fused_generation/model_structure.json"),
}

measurement_key = ["stage", "layout_fused_app", "work_shape", "layout_fused_args"]
measurements = compare_table.drop_duplicates(measurement_key).set_index(measurement_key)
penalty_rows = []

for stage, structure_file in structure_files.items():
    structures = json.loads(structure_file.read_text())["structures"]
    for structure in structures:
        workload_id = structure["workload_id"]
        config = structure["config"]
        weight = float(WORKLOAD_WEIGHTS.get(workload_id, 1.0))
        sequence_length = (
            config["prefill_seq_len"] if stage == "prefill" else config["gen_kv_len"]
        )
        for kernel in structure["kernels"]:
            layout_app = kernel["app"]
            if layout_app not in layout_to_standalone:
                continue
            work_shape = tuple(
                (field, kernel["shape"].get(field))
                for field in shape_fields[layout_app]
            )
            measured = measurements.loc[(stage, layout_app, work_shape, kernel["args"])]
            standalone_cycle = float(measured["fpga_cycle_standalone"])
            fused_cycle = float(measured["fpga_cycle_fused"])
            calls = float(kernel["calls_per_forward"])
            penalty_cycles = calls * (fused_cycle - standalone_cycle)
            penalty_rows.append({
                "workload_id": workload_id,
                "stage": stage,
                "batch": config["batch"],
                "sequence_length": sequence_length,
                "name": kernel["name"],
                "standalone_app": layout_to_standalone[layout_app],
                "layout_fused_app": layout_app,
                "work_shape": work_shape,
                "calls_per_forward": calls,
                "standalone_cycle": standalone_cycle,
                "layout_fused_cycle": fused_cycle,
                "fused_over_standalone": fused_cycle / standalone_cycle,
                "e2e_penalty_cycles": penalty_cycles,
                "positive_penalty_cycles": max(penalty_cycles, 0.0),
                "workload_weight": weight,
                "weighted_penalty_cycles": weight * penalty_cycles,
                "weighted_positive_penalty_cycles": weight * max(penalty_cycles, 0.0),
            })

penalty_detail = pd.DataFrame(penalty_rows)
penalty_detail["e2e_penalty_ms"] = (
    penalty_detail["e2e_penalty_cycles"] / (FPGA_FREQ_MHZ * 1_000.0)
)

def make_priority_ranking(group_columns):
    ranking = (
        penalty_detail.groupby(["stage", *group_columns], dropna=False)
        .agg(
            workload_points=("workload_id", "nunique"),
            priority_score_cycles=("weighted_positive_penalty_cycles", "sum"),
            signed_penalty_cycles=("weighted_penalty_cycles", "sum"),
            worst_case_penalty_cycles=("e2e_penalty_cycles", "max"),
            median_fused_over_standalone=("fused_over_standalone", "median"),
            max_fused_over_standalone=("fused_over_standalone", "max"),
        )
        .reset_index()
    )
    ranking["weighted_positive_penalty_ms"] = (
        ranking["priority_score_cycles"] / (FPGA_FREQ_MHZ * 1_000.0)
    )
    ranking["share_of_stage_positive_penalty"] = (
        ranking["priority_score_cycles"]
        / ranking.groupby("stage")["priority_score_cycles"].transform("sum")
    )
    return ranking.sort_values(
        ["stage", "priority_score_cycles"], ascending=[True, False]
    ).reset_index(drop=True)

priority_by_layout_app = make_priority_ranking(["standalone_app", "layout_fused_app"])
priority_by_kernel_name = make_priority_ranking(
    ["name", "standalone_app", "layout_fused_app"]
)

display(priority_by_layout_app)
priority_by_kernel_name

         stage        standalone_app                   layout_fused_app  workload_points  priority_score_cycles  signed_penalty_cycles  worst_case_penalty_cycles  median_fused_over_standalone  max_fused_over_standalone  weighted_positive_penalty_ms  share_of_stage_positive_penalty
0   generation  kv_cache_quant_w4a16  kv_cache_quant_layout_fused_w4a16               18           2.121109e+10           2.121109e+10               1.035010e+09                     12.945608                  13.303138                  2.121109e+05                         0.830004
1   generation               softmax               softmax_layout_fused               18           2.676172e+09           2.676172e+09               8.727961e+08                      1.455953                   1.558642                  2.676172e+04                         0.104720
2   generation              hadamard              hadamard_layout_fused               18           5.856524e+08          -6.657469e+08               4.782160e+07                      0.515968                   3.427587                  5.856524e+03                         0.022917
3   generation                 elmul                 elmul_layout_fused               18           4.897966e+08           4.897966e+08               3.054925e+07                      2.884174                   3.912283                  4.897966e+03                         0.019166
4   generation                  silu                  silu_layout_fused               18           2.412993e+08           1.957572e+08               2.565827e+07                      1.460697                   2.295428                  2.412993e+03                         0.009442
5   generation                 eladd                 eladd_layout_fused               18           1.769507e+08           1.769507e+08               8.379264e+06                      1.482717                   1.728291                  1.769507e+03                         0.006924
6   generation                  rope                  rope_layout_fused               18           1.045842e+08           1.045842e+08               3.759840e+06                      1.327452                   1.795605                  1.045842e+03                         0.004092
7   generation               rmsnorm              rms_norm_layout_fused               18           6.446515e+07           3.345062e+07               3.747232e+06                      1.208016                   1.728979                  6.446515e+02                         0.002523
8   generation           head_concat           head_concat_layout_fused               18           5.400768e+06          -1.897382e+07               9.001280e+05                      0.920648                   1.150033                  5.400768e+01                         0.000211
9      prefill               softmax               softmax_layout_fused                6           4.797863e+12           4.797863e+12               3.607226e+12                      1.407462                   1.475225                  4.797863e+07                         0.768891
10     prefill  kv_cache_quant_w4a16  kv_cache_quant_layout_fused_w4a16                6           7.030959e+11           7.030959e+11               2.873861e+11                      3.192206                   4.536585                  7.030959e+06                         0.112676
11     prefill              hadamard              hadamard_layout_fused                6           3.917995e+11          -1.584592e+12               1.993218e+11                      0.421656                   1.349708                  3.917995e+06                         0.062789
12     prefill                 eladd                 eladd_layout_fused                6           2.162135e+11           2.162135e+11               5.496202e+10                      2.285031                   2.303904                  2.162135e+06                         0.034650
13     prefill                 elmul                 elmul_layout_fused                6           1.310064e+11           1.310064e+11               6.655973e+10                      1.448982                   1.449328                  1.310064e+06                         0.020995
14     prefill           head_concat           head_concat_layout_fused                6           0.000000e+00          -8.967359e+10              -1.472203e+09                      0.210376                   0.218829                  0.000000e+00                         0.000000
15     prefill               rmsnorm              rms_norm_layout_fused                6           0.000000e+00          -8.304147e+10              -6.559358e+08                      0.759912                   0.761007                  0.000000e+00                         0.000000
16     prefill                  rope                  rope_layout_fused                6           0.000000e+00          -3.926166e+10              -1.187982e+08                      0.892023                   0.896913                  0.000000e+00                         0.000000
17     prefill                  silu                  silu_layout_fused                6           0.000000e+00          -4.134741e+11              -6.569223e+09                      0.474801                   0.474930                  0.000000e+00                         0.000000

         stage                               name        standalone_app                   layout_fused_app  workload_points  priority_score_cycles  signed_penalty_cycles  worst_case_penalty_cycles  median_fused_over_standalone  max_fused_over_standalone  weighted_positive_penalty_ms  share_of_stage_positive_penalty
0   generation  kv_cache_quant_v_cache_to_attn_pv  kv_cache_quant_w4a16  kv_cache_quant_layout_fused_w4a16               18           1.065767e+10           1.065767e+10               1.035010e+09                     13.153723                  13.303138                  1.065767e+05                         0.417042
1   generation  kv_cache_quant_rope_k_to_attn_qkT  kv_cache_quant_w4a16  kv_cache_quant_layout_fused_w4a16               18           1.055342e+10           1.055342e+10               1.027239e+09                     12.762476                  13.063337                  1.055342e+05                         0.412962
2   generation                       attn_softmax               softmax               softmax_layout_fused               18           2.676172e+09           2.676172e+09               8.727961e+08                      1.455953                   1.558642                  2.676172e+04                         0.104720
3   generation          spinquant_r4_mlp_hadamard              hadamard              hadamard_layout_fused               18           5.856524e+08           5.856524e+08               4.782160e+07                      1.944469                   3.427587                  5.856524e+03                         0.022917
4   generation                          mlp_elmul                 elmul                 elmul_layout_fused               18           4.897966e+08           4.897966e+08               3.054925e+07                      2.884174                   3.912283                  4.897966e+03                         0.019166
5   generation                           mlp_silu                  silu                  silu_layout_fused               18           2.412993e+08           1.957572e+08               2.565827e+07                      1.460697                   2.295428                  2.412993e+03                         0.009442
6   generation                      residual_attn                 eladd                 eladd_layout_fused               18           8.847533e+07           8.847533e+07               8.379264e+06                      1.482717                   1.728291                  8.847533e+02                         0.003462
7   generation                       residual_ffn                 eladd                 eladd_layout_fused               18           8.847533e+07           8.847533e+07               8.379264e+06                      1.482717                   1.728291                  8.847533e+02                         0.003462
8   generation                             rope_k                  rope                  rope_layout_fused               18           5.681635e+07           5.681635e+07               3.759840e+06                      1.553814                   1.795605                  5.681635e+02                         0.002223
9   generation                             rope_q                  rope                  rope_layout_fused               18           4.776787e+07           4.776787e+07               2.862880e+06                      1.218782                   1.355859                  4.776787e+02                         0.001869
10  generation                    input_layernorm               rmsnorm              rms_norm_layout_fused               18           3.223258e+07           1.672531e+07               3.747232e+06                      1.208016                   1.728979                  3.223258e+02                         0.001261
11  generation           post_attention_layernorm               rmsnorm              rms_norm_layout_fused               18           3.223258e+07           1.672531e+07               3.747232e+06                      1.208016                   1.728979                  3.223258e+02                         0.001261
12  generation                   attn_head_concat           head_concat           head_concat_layout_fused               18           5.400768e+06          -1.897382e+07               9.001280e+05                      0.920648                   1.150033                  5.400768e+01                         0.000211
13  generation            spinquant_r3_k_hadamard              hadamard              hadamard_layout_fused               18           0.000000e+00          -2.412300e+08              -5.385888e+06                      0.515968                   0.577090                  0.000000e+00                         0.000000
14  generation            spinquant_r3_q_hadamard              hadamard              hadamard_layout_fused               18           0.000000e+00          -1.010169e+09              -2.340294e+07                      0.451972                   0.473745                  0.000000e+00                         0.000000
15     prefill                       attn_softmax               softmax               softmax_layout_fused                6           4.797863e+12           4.797863e+12               3.607226e+12                      1.407462                   1.475225                  4.797863e+07                         0.768891
16     prefill  kv_cache_quant_v_cache_to_attn_pv  kv_cache_quant_w4a16  kv_cache_quant_layout_fused_w4a16                6           5.664670e+11           5.664670e+11               2.873861e+11                      4.501986                   4.536585                  5.664670e+06                         0.090780
17     prefill          spinquant_r4_mlp_hadamard              hadamard              hadamard_layout_fused                6           3.917995e+11           3.917995e+11               1.993218e+11                      1.348059                   1.349708                  3.917995e+06                         0.062789
18     prefill  kv_cache_quant_rope_k_to_attn_qkT  kv_cache_quant_w4a16  kv_cache_quant_layout_fused_w4a16                6           1.366289e+11           1.366289e+11               6.850649e+10                      1.863507                   1.899056                  1.366289e+06                         0.021896
19     prefill                          mlp_elmul                 elmul                 elmul_layout_fused                6           1.310064e+11           1.310064e+11               6.655973e+10                      1.448982                   1.449328                  1.310064e+06                         0.020995
20     prefill                      residual_attn                 eladd                 eladd_layout_fused                6           1.081068e+11           1.081068e+11               5.496202e+10                      2.285031                   2.303904                  1.081068e+06                         0.017325
21     prefill                       residual_ffn                 eladd                 eladd_layout_fused                6           1.081068e+11           1.081068e+11               5.496202e+10                      2.285031                   2.303904                  1.081068e+06                         0.017325
22     prefill                   attn_head_concat           head_concat           head_concat_layout_fused                6           0.000000e+00          -8.967359e+10              -1.472203e+09                      0.210376                   0.218829                  0.000000e+00                         0.000000
23     prefill                    input_layernorm               rmsnorm              rms_norm_layout_fused                6           0.000000e+00          -4.152074e+10              -6.559358e+08                      0.759912                   0.761007                  0.000000e+00                         0.000000
24     prefill                           mlp_silu                  silu                  silu_layout_fused                6           0.000000e+00          -4.134741e+11              -6.569223e+09                      0.474801                   0.474930                  0.000000e+00                         0.000000
25     prefill           post_attention_layernorm               rmsnorm              rms_norm_layout_fused                6           0.000000e+00          -4.152074e+10              -6.559358e+08                      0.759912                   0.761007                  0.000000e+00                         0.000000
26     prefill                             rope_k                  rope                  rope_layout_fused                6           0.000000e+00          -8.119330e+09              -1.187982e+08                      0.888813                   0.896913                  0.000000e+00                         0.000000
27     prefill                             rope_q                  rope                  rope_layout_fused                6           0.000000e+00          -3.114233e+10              -4.851342e+08                      0.893256                   0.894326                  0.000000e+00                         0.000000
28     prefill            spinquant_r3_k_hadamard              hadamard              hadamard_layout_fused                6           0.000000e+00          -3.952867e+11              -6.279000e+09                      0.421538                   0.421741                  0.000000e+00                         0.000000
29     prefill            spinquant_r3_q_hadamard              hadamard              hadamard_layout_fused                6           0.000000e+00          -1.581104e+12              -2.509166e+10                      0.421578                   0.421744                  0.000000e+00                         0.000000

In [ ]:
"hadamard_base"
"vecadd"
"detile_output"
"eldiv"
"eladd_layout_fused"
"eladd"
"hadamard"
"softmax"
"elmul_layout_fused"
"head_concat_layout_fused"
"elreduce"
"silu"
"silu"
"silu"
"tile_weight_w4a16"
"tile_scale_zp_w4a16"
"kv_cache_quant_w4a16"
"head_concat"
"rmsnorm"
"kv_cache_dequant_w4a16"
"rms_norm_layout_fused"
"hadamard_layout_fused"
"softmax_layout_fused"
"elsub"
"elscalar"
"tile_input_a"
"elmul"
"rope"
"silu_layout_fused"
"silu_layout_fused"
"silu_layout_fused"
"dropout"
"rope_layout_fused"
"kv_cache_quant_layout_fused_w4a16"
"elunary"
def del_vector_kernels(path):
  """
  Delete stale vector kernels.
  """

In [73]:
df = pd.read_csv("./outputs_llama2_main/C4/raw_db.csv")
new_df = df[df["app"]=="fpint_gemm_ffn_hw"]
new_df["xclbin_sha256"] = "d80cb0bb876104aa2163fedf48f297b8020f2d5c82df6350a783f5f87d6d9674"
new_df.to_csv("./outputs_llama2_main/C4/raw_db.csv", index=False)

/tmp/ipykernel_3480428/3734036332.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df["xclbin_sha256"] = "d80cb0bb876104aa2163fedf48f297b8020f2d5c82df6350a783f5f87d6d9674"

In [ ]:
df = pd.read_csv("./outputs_llama3_main/C4/raw_db.csv")
# new_df = df[(df["kind"]!="dequantization") & (df["kind"]!="quantization")]
# new_df = df[df["app"]=="fpint_gemm_ffn_hw"]
new_df=df
new_df["xclbin_sha256"] = "d80cb0bb876104aa2163fedf48f297b8020f2d5c82df6350a783f5f87d6d9674"
new_df.to_csv("./outputs_llama3_main/C4/raw_db.csv", index=False)

In [ ]:
df = pd.read_csv("./outputs_llama2_main/C4/raw_db.csv")